name: Test Build

on:
  pull_request:

jobs:
  matrix-builder:
    runs-on: ubuntu-24.04
    outputs:
      includes: ${{ steps.builder.outputs.includes }}
    steps:
      - name: Build Matrix
        id: builder
        uses: regolith-linux/actions/build-matrix@enhance-build-matrix
        with:
          name: "${{ github.event.repository.name }}"
          ref: "${{ github.base_ref }}"
          # arch: "amd64"
          arch: "amd64 arm64"
          stage: "unstable"

  # test:
  #   runs-on: ubuntu-24.04
  #   container: "ubuntu:oracular"
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - run: |
  #         pwd
  #         ls -la
  #         touch $(pwd)/in-pwd
  #         ls -la
  #         echo "==================================="
  #         WORKSPACE_ROOT_PATH=$(realpath "$(realpath "$(pwd)")/../")
  #         echo $WORKSPACE_ROOT_PATH
  #         ls -la "$WORKSPACE_ROOT_PATH"
  #         touch $WORKSPACE_ROOT_PATH/in-workspace
  #         ls -la "$WORKSPACE_ROOT_PATH"
  #     - run: |
  #         pwd
  #         ls -la
  #         echo "==================================="
  #         WORKSPACE_ROOT_PATH=$(realpath "$(realpath "$(pwd)")/../")
  #         echo $WORKSPACE_ROOT_PATH
  #         ls -la "$WORKSPACE_ROOT_PATH"

  # source:
  #   runs-on: ubuntu-24.04
  #   needs: test
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - run: |
  #         pwd
  #         ls -la
  #         echo "==================================="
  #         WORKSPACE_ROOT_PATH=$(realpath "$(realpath "$(pwd)")/../")
  #         echo $WORKSPACE_ROOT_PATH
  #         ls -la "$WORKSPACE_ROOT_PATH"

  build:
    runs-on: ubuntu-24.04
    # runs-on: [self-hosted, Linux, "${{ matrix.arch }}", noble] 
    # container: "${{ matrix.distro }}:${{ matrix.codename }}"
    needs: matrix-builder
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix-builder.outputs.includes) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Package
        uses: regolith-linux/actions/build-package@enhance-build-matrix
        with:
          name: "${{ github.event.repository.name }}"
          distro: "${{ matrix.distro }}"
          codename: "${{ matrix.codename }}"
          stage: "unstable"
          suite: "unstable"
          component: "main"
          arch: "${{ matrix.arch }}"
          gpg-key: "${{ secrets.PACKAGE_PRIVATE_KEY2 }}"

  #     - name: Upload Files
  #       uses: regolith-linux/actions/upload-files@main
  #       with:
  #         server-address: "${{ secrets.KAMATERA_HOSTNAME2 }}"
  #         server-username: "${{ secrets.KAMATERA_USERNAME }}"
  #         server-ssh-key: "${{ secrets.KAMATERA_SSH_KEY }}"



  # package:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       arch:
  #         - docker: amd64  # used by docker create --platform
  #         - docker: arm64
  #       distro:
  #         - container: "ubuntu:jammy"
  #         - container: "ubuntu:focal"

  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #       with:
  #         platforms: ${{ matrix.arch }}

  #     - name: Run in Docker
  #       run: |
  #         docker run \
  #           --rm \
  #           -v $(pwd):/${{ github.workspace }} \
  #           -w ${{ github.workspace }} \
  #           --platform linux/${{ matrix.arch }} \
  #           ${{ matrix.distro }} \
  #           uname -a

  # sources:
  #   runs-on: ubuntu-24.04
  #   needs: build
  #   steps:
  #     - name: find files
  #       run: |
  #         find "$(realpath "$(realpath "${{ github.workspace }}")/../")"
